rCSRSaulCantoral:
  hostname: "10.134.18.213"
  username: "C27747"
  password: "IzanagI11."
  port: 22
  platform: "zte"
  data:
    real_alias: "rCSRSaulCantoral"
    original_ip: "10.134.18.213"
  groups:
    - zte_routers


rCSRCruzdeAvaya:
  hostname: "10.134.2.93"
  username: "C27747"
  password: "IzanagI11."
  port: 22
  platform: "zte"
  data:
    real_alias: "rCSRCruzdeAvaya"
    original_ip: "10.134.2.93"
  groups:
    - zte_routers


rCSRLosLloques:
  hostname: "10.134.0.169"
  username: "C27747"
  password: "IzanagI11."
  port: 22
  platform: "zte"
  data:
    real_alias: "rCSRLosLloques"
    original_ip: "10.134.0.169"
  groups:
    - zte_routers


rCSREntradaHuamachuco:
  hostname: "10.134.5.213"
  username: "C27747"
  password: "IzanagI11."
  port: 22
  platform: "zte"
  data:
    real_alias: "rCSREntradaHuamachuco"
    original_ip: "10.134.5.213"
  groups:
    - zte_routers


rCSRLosSauces2:
  hostname: "10.253.14.33"
  username: "C27747"
  password: "IzanagI11."
  port: 22
  platform: "zte"
  data:
    real_alias: "rCSRLosSauces2"
    original_ip: "10.253.14.33"
  groups:
    - zte_routers


